### ISSUE TITLE
Implementação da classe Disciplina POJO

### ISSUE THREAD

**Issue by ValdemirNeto0** [ValdemirNeto0/Projeto_ADS_Chicout#11]

**Comment by Rycks012** [comment]
// Criando classe 
        public class Disciplina {   
        private String carga_horaria, nome_disciplina, id_disciplina;
// Construtor sem parametros 
    public Disciplina(){
        carga_horaria ="";
        nome_disciplina ="";
        id_disciplina ="";
    } // Get e Set
    public String getCarga_horaria(){
        return carga_horaria;
    }
    public void setCarga_horaria(String carga_horaria) {
        this.carga_horaria = carga_horaria;
    }
    public String getNome_disciplina(){
        return nome_disciplina;
    }
    public void setNome_disciplina(String nome_disciplina) {
        this.nome_disciplina = carga_horaria;
    }
    public String getId_disciplina(){
        return id_disciplina;
    }
    public void setId_disciplina(String id_disciplina){
        this.id_disciplina = id_disciplina;
    }
}
