### ISSUE TITLE
Criação das classes que representam cada uma das entidades de dados

### ISSUE THREAD

**Issue by fchicout** [ValdemirNeto0/Projeto_ADS_Chicout#3]
Criação das classes Java que representam cada uma das entidades de dados, com seus atributos, em modo [POJO](http://www.universidadejava.com.br/java/java-pojo/#:~:text=Um%20POJO%20%C3%A9%20um%20JavaBean,um%20construtor%20default%20automaticamente)

**Comment by ValdemirNeto0** [comment]
Classes implementadas com sucesso.
